version: '3.8'

services:
  cojakeons-plus:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cojakeons-plus
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - cojakeons-network

networks:
  cojakeons-network:
    driver: bridge
